use std::fs;
use std::path::{Path, PathBuf};

use crate::service::forge::ForgeState;
use crate::service::ghosttype_log;

pub fn rules_output_path() -> PathBuf {
    std::env::var("FORGE_UDEV_RULES")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/etc/forge/udev/99-forge.rules"))
}

pub fn generate_rules(state: &ForgeState) -> Result<(), String> {
    let mut lines = vec![
        "# Generated by The Forge — do not edit".to_string(),
        String::new(),
    ];

    for (kernel, service) in state.device_units() {
        lines.push(format!(
            r#"KERNEL=="{}", ACTION=="add", TAG+="forge""#,
            kernel
        ));
        lines.push(format!(
            r#"KERNEL=="{}", ACTION=="add", RUN+="/usr/bin/forgectl start {}""#,
            kernel, service
        ));
        lines.push(String::new());
    }

    if lines.len() <= 2 {
        return Ok(());
    }

    let content = lines.join("\n");
    let mut candidates = vec![rules_output_path()];
    let runtime = PathBuf::from("/run/forge/udev/99-forge.rules");
    if !candidates.contains(&runtime) {
        candidates.push(runtime);
    }

    let mut last_err = String::from("no writable udev rules path");
    for path in candidates {
        if let Some(parent) = path.parent() {
            if let Err(e) = fs::create_dir_all(parent) {
                last_err = format!("{parent:?}: {e}");
                continue;
            }
        }
        match fs::write(&path, &content) {
            Ok(()) => {
                ghosttype_log("UDEV", &format!("Wrote rules to {}", path.display()));
                if command_exists("udevadm") {
                    let _ = std::process::Command::new("udevadm")
                        .arg("control")
                        .arg("--reload-rules")
                        .status();
                }
                return Ok(());
            }
            Err(e) => {
                last_err = format!("{}: {e}", path.display());
            }
        }
    }

    Err(last_err)
}

#[allow(dead_code)]
pub fn install_reference_rules(out_dir: &Path) -> Result<(), String> {
    fs::create_dir_all(out_dir).map_err(|e| e.to_string())?;
    fs::write(
        out_dir.join("99-forge-logind.rules"),
        r#"# Tag forge-logind sessions
SUBSYSTEM=="misc", KERNEL=="fuse", TAG+="forge"
"#,
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}

fn command_exists(name: &str) -> bool {
    std::env::var_os("PATH")
        .map(|paths| std::env::split_paths(&paths).any(|dir| dir.join(name).is_file()))
        .unwrap_or(false)
}
