# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the netinstall module.
---
groupsUrl: local

groups:
  - name: "Additional Desktop Environments"
    description: "Sisyphus OS defaults to COSMIC. Select any additional environments to install alongside it."
    hidden: false
    selected: false
    subgroups:
      - name: "GNOME"
        description: "The standard Fedora GNOME workstation experience."
        selected: false
        packages:
          - "@gnome-desktop"
      - name: "KDE Plasma"
        description: "The highly customizable KDE Plasma desktop."
        selected: false
        packages:
          - "@kde-desktop"
