[service]
name = "udev-settle"
# Wait for udev queue to empty. Many services (especially display/graphics) wait implicitly or explicitly for this.
exec = "/usr/bin/udevadm"
args = ["settle", "--timeout=30"]
after = ["udev-trigger"]
type = "oneshot"
restart = "no"
