---
defaultGroups:
    - name: wheel
      must_exist: false
      system: true
    - name: users
      must_exist: false
      system: true
    - name: video
      must_exist: false
      system: true
    - name: render
      must_exist: false
      system: true
    - name: input
      must_exist: false
      system: true
    - name: seat
      must_exist: false
      system: true

doAutologin: false
sudoersGroup: wheel