---
showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
    requiredStorage: 8.0
    requiredRam: 2.0
    internetCheckUrl: https://fedoraproject.org/static/hotspot.txt
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root