[service]
name = "logind"
exec = "/usr/libexec/forge/start-logind.sh"
args = []
type = "notify"
requires = ["systemd1-stub"]
after = ["forge-early", "dbus", "systemd1-stub", "udev"]
restart = "on-failure"