[service]
name = "wpa_supplicant"
description = "WPA Supplicant daemon"
exec = "/usr/sbin/wpa_supplicant"
args = ["-u", "-s", "-O", "/run/wpa_supplicant"]
type = "dbus"
bus-name = "fi.w1.wpa_supplicant1"
after = ["dbus", "udev"]
restart = "on-failure"
